export const MAX = {
	EMAIL_LEN: 150,
	USERNAME_LEN: 50,
	PASSWORD_LEN: 50,
	TAG_NAME: 30,

	VOTE_TITLE: 200,
	VOTE_DESC: 500,
	VOTE_TAG: 5,
	ANSWER_OPTIONS: 20,
	OPTION_PHOTO_SIZE: 1, // 1MB
	USER_AVT_SIZE: 1.5,
	OPTION_LABEL: 100,
	COMMENT_LEN: 500,
};

export const MIN = {
	PASSWORD_LEN: 8,
};

export const VERIFY_CODE_LEN = 6;
