export const MAX = {
	EMAIL_LEN: 150,
	USERNAME_LEN: 50,
	PASSWORD_LEN: 50,

	VOTE_TITLE: 150,
	VOTE_DESC: 250,
	VOTE_TAG: 5,
	ANSWER_OPTIONS: 10,
	OPTION_PHOTO_SIZE: 1, // 1MB
	OPTION_LABEL: 100,
};

export const MIN = {
	PASSWORD_LEN: 8,
};
